package ServerApp;


/**
* ServerApp/Server_interfaceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from G:/workspace/COMP6231-A2-DEMS/src/ServerApp.idl
* Sunday, June 9, 2019 7:09:14 PM EDT
*/

abstract public class Server_interfaceHelper
{
  private static String  _id = "IDL:ServerApp/Server_interface:1.0";

  public static void insert (org.omg.CORBA.Any a, ServerApp.Server_interface that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ServerApp.Server_interface extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (ServerApp.Server_interfaceHelper.id (), "Server_interface");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ServerApp.Server_interface read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_Server_interfaceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ServerApp.Server_interface value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static ServerApp.Server_interface narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ServerApp.Server_interface)
      return (ServerApp.Server_interface)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ServerApp._Server_interfaceStub stub = new ServerApp._Server_interfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static ServerApp.Server_interface unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ServerApp.Server_interface)
      return (ServerApp.Server_interface)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ServerApp._Server_interfaceStub stub = new ServerApp._Server_interfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
