package ServerApp;

/**
* ServerApp/Server_interfaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from G:/workspace/COMP6231-A2-DEMS/src/ServerApp.idl
* Sunday, June 9, 2019 7:09:14 PM EDT
*/

public final class Server_interfaceHolder implements org.omg.CORBA.portable.Streamable
{
  public ServerApp.Server_interface value = null;

  public Server_interfaceHolder ()
  {
  }

  public Server_interfaceHolder (ServerApp.Server_interface initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ServerApp.Server_interfaceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ServerApp.Server_interfaceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ServerApp.Server_interfaceHelper.type ();
  }

}
