package ServerApp;


/**
* ServerApp/Server_interface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from G:/workspace/COMP6231-A2-DEMS/src/ServerApp.idl
* Sunday, June 9, 2019 7:09:14 PM EDT
*/

public interface Server_interface extends Server_interfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Server_interface
